name: Insurance CI Pipeline

# Trigger conditions
on:
  push:
    branches: [ "main", "master" ] 
  pull_request:
    branches: [ "main", "master" ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4


    - name: Docker configuration check
      run: docker compose config

    - name: Image build
      run: docker compose build
